---
title: "Insect_GeneralSummaries"
output: html_document
date: "2024-02-08"
---


```{r}

library(data.table)
library(tidyverse)
library(beepr)
library(lubridate)
library(purrr)
library(janitor)
#renv::install("rstudio/renv")
library(renv)
library(stringr)
library(beepr)
library(kableExtra)
library(papeR)
library(skimr)
library(vtable)
library(ggdark)
library(RColorBrewer)
library(cowplot)
library(readxl)
library(readr)
library(ggstats)
library(ggpmisc)
library(gginnards)
library(ggplot2)
library(colorBlindness)
library(vegan) 
library(TMB)
library(glmmTMB)
library(DHARMa)

## Setup output directory 
output <- "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/ForDryad/4.FiguresTables/Outputs/"

file.name <- "GeneralFiguresSummaries"

todays_date <- Sys.Date()
 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
dir.name
 
output_today <- dir.name
output_today

dir.create(output_today)
output_today
```

###########################################################
## Unaggregated bat acoustic data
###########################################################
```{r}

rawbat <- read_csv("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/Inputs/ManualAnalaysis21_22_combined_datetime_PlotType_Guild.csv", 
     col_types = cols(...1 = col_skip()))
# 108989 

rawbat <- rawbat %>% mutate(AUTO.ID = factor(AUTO.ID),
                            manual.id = factor(manual.id),
                            behavior = factor(behavior),
                            guild = factor(guild),
                            year = factor(year),
                            Site = factor(Site), 
                        SitePlot = factor(SitePlot), 
                        PlotType = factor(PlotType)) 

levels(rawbat$manual.id)
table(rawbat$manual.id)
levels(rawbat$AUTO.ID)
# 5116 NAs for AUTO.ID and INDIR for recordings that had multiple bats/were parsed. Fix this here:

### Subset for the NA observations 
nas <- rawbat %>% filter(is.na(AUTO.ID)) # 5116
summary(nas)

# Select the auto id and indir for these files 
fix <- nas %>% select(file.name) %>% distinct() # 5029
fix1 <- left_join(fix, rawbat) %>% drop_na()
summary(fix1)
fix2 <- fix1 %>% select(file.name, INDIR, AUTO.ID) %>% distinct()

# Attach the indir and autoid for wher previously there were nas 
nas1 <- nas %>% select(-c(AUTO.ID, INDIR)) 
summary(nas1)
nas2 <- left_join(nas1, fix2)
summary(nas2)

# Remove the nas from the rawbat dataset and then replace with actual values
rawbat1 <- rawbat %>% drop_na(AUTO.ID)
dim(rawbat)
#108989     22

dim(rawbat1)
#103873     22
#108989 - 103873 = 5116, good 

dim(nas2)
#5116   22
# good

rawbat2 <- merge(rawbat1, nas2, all = TRUE)
dim(rawbat2)
#108989     22, good

summary(rawbat2) 

rawbat3 <- rawbat2 %>% mutate(auto = factor(case_when(
  AUTO.ID == "BARBAR" ~ "BABA",
  AUTO.ID == "EPTNIL" ~ "EPNI",
  AUTO.ID == "EPTSER" ~ "EPSE",
  AUTO.ID %in% c("MYOALC", "MYOBEC", "MYOBRA",
                 "MYODAS", "MYODAU", "MYOMYO", 
                 "MYOMYS", "MYONAT") ~ "MYOT",
  AUTO.ID == "NYCNOC" ~ "NYNO",
  AUTO.ID == "NYCLEI" ~ "NYLE",
  AUTO.ID == "PIPNAT" ~ "PINA", 
  AUTO.ID == "PIPPIP" ~ "PIPI", 
  AUTO.ID == "PIPPYG" ~ "PIPY", 
  AUTO.ID == "PLEAUR" ~ "PAUR",
  AUTO.ID == "PLEAUS" ~ "PAUS", 
  AUTO.ID == "VESMUR" ~ "VEMU", 
  AUTO.ID == "NoID" ~ "NoID"
))) %>% 
  mutate(auto.guild = factor(case_when(
  AUTO.ID == "BARBAR" ~ "SRE",
  AUTO.ID == "EPTNIL" ~ "LRE",
  AUTO.ID == "EPTSER" ~ "LRE",
  AUTO.ID %in% c("MYOALC", "MYOBEC", "MYOBRA",
                 "MYODAS", "MYODAU", "MYOMYO", 
                 "MYOMYS", "MYONAT") ~ "SRE",
  AUTO.ID == "NYCNOC" ~ "LRE",
  AUTO.ID == "NYCLEI" ~ "LRE",
  AUTO.ID == "PIPNAT" ~ "MRE", 
  AUTO.ID == "PIPPIP" ~ "MRE", 
  AUTO.ID == "PIPPYG" ~ "MRE", 
  AUTO.ID == "PLEAUR" ~ "SRE",
  AUTO.ID == "PLEAUS" ~ "SRE", 
  AUTO.ID == "VESMUR" ~ "LRE", 
  AUTO.ID == "NoID" ~ "NoID"  
  ))) 

summary(rawbat3)


rbats <- rawbat3

```


