---
title: "BatCaptures"
output: html_document
date: "2024-02-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(data.table)
library(tidyverse)
library(beepr)
library(lubridate)
library(purrr)
library(janitor)
#renv::install("rstudio/renv")
library(renv)
library(stringr)
library(beepr)
library(kableExtra)
library(papeR)
library(skimr)
library(vtable)
library(ggdark)
library(RColorBrewer)
library(cowplot)
library(readxl)
library(readr)
library(ggstats)
library(ggpmisc)
library(gginnards)
library(ggplot2)
library(colorBlindness)
library(vegan) 
library(TMB)
library(glmmTMB)
library(DHARMa)
library(performance)
library(car)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(modelsummary)
library(gt)
library(beepr)

## Setup output directory 
output <- "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/ForDryad/4.FiguresTables/Outputs/"

file.name <- "BatCaptures"

todays_date <- Sys.Date()
 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
dir.name
 
output_today <- dir.name
output_today

dir.create(output_today)
output_today

```


## Figures and summaries 
```{r}

# Reportin on bat capture data 

caps <- read_excel("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/ForDryad/4.FiguresTables/Inputs/BatCaptures.xlsx")

caps$Repro <- factor(caps$Repro)
caps$Sex <- factor(caps$Sex)
caps$date <- as.Date(caps$Date, format = "%d.%m.%Y")

ggplot(caps, aes(x = date, y = Repro, color = Sex)) +
  geom_point(size = 3) + xlab("") + theme_minimal()

table(caps$Repro)

## Overview of survey effort and capture success 
caps <- read_delim("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/Inputs/MistNettingOverview.csv", 
     delim = ";", escape_double = FALSE, col_types = cols(Site = col_character()), 
     trim_ws = TRUE)

caps$Site <- factor(caps$Site) 
caps$nhours <- caps$`N hours`
caps$nnets <- caps$`N nets`

nhours <- ggplot(caps, aes(x = nhours, y = Total)) + 
  stat_poly_line(color = "#DAB82A") +
  stat_poly_eq() +
  geom_point() +
  theme_minimal() + 
  xlab("Number of net hours") + 
  ylab("Number of bat captures") +
  theme(text = element_text(size = 12))

nnets <- ggplot(caps, aes(x = nnets, y = Total)) + 
  stat_poly_line(color = "#DAB82A") +
  stat_poly_eq() +
  geom_point() +
  theme_minimal() + 
  xlab("Number of nets") + 
  ylab("Number of bat captures") +
  theme(text = element_text(size = 12))

fig4 <- plot_grid(nhours, nnets, nrow = 2, labels = c("a.", "b."))
fig4

```

