---
title: "CommunityMatrix"
output: html_document
date: "2024-02-03"
---


## Goals 

-NMDS ordination of bat taxa occurances across site plot nights


```{r}
library(data.table)
library(tidyverse)
library(beepr)
library(lubridate)
library(purrr)
library(janitor)
#renv::install("rstudio/renv")
library(renv)
library(stringr)
library(beepr)
library(kableExtra)
library(papeR)
library(skimr)
library(vtable)
library(ggdark)
library(RColorBrewer)
library(cowplot)
library(readxl)
library(readr)
library(ggstats)
library(ggpmisc)
library(gginnards)
library(ggplot2)
library(colorBlindness)
library(vegan) 
library(gt)
library(beepr)
library(BiodiversityR)


## Setup output directory 
output <- "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/ForDryad/4.FiguresTables/Outputs/"

file.name <- "CommunityMatrix"

todays_date <- Sys.Date()
 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
dir.name
 
output_today <- dir.name
output_today

dir.create(output_today)
output_today

```



## Import and tidy
```{r}
bats <- read_csv("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/ForDryad/2.AggregationCombineCovariates/NightAggregateBats_DensityManuscript/Outputs/NightAggBats_2024-02-01/DensityBats_ForestPhoto.csv", 
 col_types = cols(...1 = col_skip()))

bats <- bats %>% dplyr::mutate(jnight = yday(night), 
                        SitePlotYear = factor(SitePlotYear),
                        Site = factor(Site), 
                        SitePlot = factor(SitePlot), 
                        PlotType = factor(PlotType),
                        year = factor(year), 
                        jnight.f = factor(jnight),
                          manual.id = factor(manual.id), 
                          behavior = factor(behavior), 
                          guild = factor(guild)) %>%
  dplyr::mutate(s.temperature = as.numeric(scale(temperature)),
         s.rainfall = as.numeric(scale(rainfall)),
         s.PC1 = as.numeric(scale(PC1))) 

summary(bats)

dim(bats)
# 244470     33
sum(bats$batpass)
# 106519

## Color palette for later 
bats$PlotType <- factor(bats$PlotType, levels=c("Open", "Interior", "Canopy"))
levels(bats$PlotType)
plot.cols <- c("#F57969", "#669F85", "#6D5AA1") 

## Print out plot type legend 
summary(bats$jnight)
 
### Create a "Season" categorical variable split into three categories evenly:
bats1 <- bats %>% 
  dplyr::mutate(season = factor(case_when(
    jnight %in% 124:170 ~ "Early", 
    jnight %in% 171:217 ~ "Medium", 
    jnight %in% 218:263 ~ "Late"))) %>% 
  dplyr::mutate(season = 
                  factor(season, levels=c("Early", "Medium", "Late"))) 
summary(bats1)

summary(bats1$season) 
# Early Medium   Late 
# 80970  93510  69990
 levels(bats1$season)
 
bats1$siteplotnight <- factor(paste0(bats1$SitePlotYear, "-", bats1$night)) 
bats1$siteplotseason <- factor(paste0(bats1$SitePlotYear, "-", bats1$season)) 

summary(bats1$siteplotnight) # 8149 levels
summary(bats1$siteplotseason) # 202 levels 

```


## Wrangle an occurence matrix and run the NMDS 
rows = site - plot - nights
columns = bat taxa 
n = number of times each taxa was identified per site - plot - night 

https://rstudio-pubs-static.s3.amazonaws.com/545184_87dac405e4b145f8adff2c4a99e938fc.html 

https://stackoverflow.com/questions/13281303/creating-co-occurrence-matrix

https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html#3_Example_1:_Dune_meadow_data  


```{r}

bats2 <- bats1 %>% filter(batpass>0) %>% 
  select(-behavior)  %>% 
  group_by(SitePlotYear, manual.id) %>% 
  dplyr::summarise(batpass1 = sum(batpass)) %>% distinct() 
dim(bats2)
#596 3

batmat <- spread(bats2, manual.id, batpass1, fill = 0)
batmat$SitePlotYear <- as.character(batmat$SitePlotYear)
batmat1 <- batmat %>% remove_rownames %>% column_to_rownames(var="SitePlotYear") %>% as.data.frame()
summary(batmat1)
#69 obs 

b.mds <- metaMDS(batmat1, distance = "bray",
                   k = 3,
          maxit = 999,
          trymax = 500,
          wascores = TRUE)
# saveRDS(b.mds, file = "./BatNMDS_season.RDS")

goodness(b.mds) # Produces a results of test statistics for goodness of fit for each point

stressplot(b.mds) # Produces a Shepards diagram


bat.env <- bats1 %>% select(SitePlotYear, Site, PlotType, year) %>% distinct()

plot1 <- ordiplot(b.mds)
sites.long1 <- sites.long(plot1, env.data = bat.env) 

## Euclidean distance with coord_fixed
plotgg1 <- ggplot(data=sites.long1, 
               aes(x=axis1, y=axis2, color=PlotType, fill = PlotType)) + 
    xlab("NMDS1") +
    ylab("NMDS2") +  
    geom_point(aes(shape=PlotType), 
               size=3) +
  theme_minimal() + 
  scale_color_manual(values = plot.cols) 

plotgg1 + 
  stat_ellipse(type = "euclid", geom = "polygon", alpha = 0.4) +
  coord_fixed() + 
  scale_fill_manual(values = plot.cols) 


## Normal distance
plotgg1 <- ggplot(data=sites.long1, 
               aes(x=axis1, y=axis2, color=PlotType, fill = PlotType)) + 
    xlab("NMDS1") +
    ylab("NMDS2") +  
    geom_point(aes(shape=PlotType), 
               size=3) +
  theme_classic() + 
  theme(text = element_text(size = 25)) + 
  scale_color_manual(values = plot.cols) +
  theme(legend.position = "bottom") + 
  theme(legend.title=element_blank())
  

plotgg2 <- plotgg1 + 
  stat_ellipse(type = "norm", geom = "polygon", alpha = 0.2) +
  coord_fixed() + 
  scale_fill_manual(values = plot.cols) 

plotgg2

#output_today
ggsave(path = output_today, filename = "NMDS.tiff", width = 10, height = 10, device='tiff', dpi=300) 
# Plot with site variation 

## arrange sites according to increasing PC1 
batpc1 <- bats1 %>% group_by(Site) %>%  
  dplyr::summarise(pc1 = mean(PC1)) %>% arrange(pc1) 
SiteOrder <- batpc1$Site

bdf <- bats1 %>%  select(c(SitePlotYear, Site, SitePlot, PlotType, year)) %>% distinct()

batpc2 <- left_join(bdf, batpc1) %>% distinct() %>% arrange(pc1)

batsum <- bats1 %>% group_by(SitePlotYear) %>% 
  dplyr::summarize(batpass = sum(batpass)) 

batpc3 <- left_join(batpc2, batsum ) %>% arrange(pc1)

neworder <- unique(batpc3$SitePlot)
neworder

batpc3$SitePlot1 <- factor(batpc3$SitePlot, levels = neworder)
levels(batpc3$SitePlot1)

sites <- ggplot(batpc3) + 
  geom_col(aes(x = SitePlot1, y = batpass, fill = PlotType, alpha = year), 
           position = "dodge") +
  facet_wrap(~PlotType,  scales = "free_x") + 
  theme(strip.text.x = element_text(size = 40)) + 
  theme_classic() + 
  theme(legend.position = "none") +
  theme(text=element_text(size=20)) + 
  scale_fill_manual(name = "Habitat", values = plot.cols) + 
  scale_alpha_discrete(range = c(1, 0.8)) + 
  xlab("Sites") + ylab("Total bat passes") + 
  scale_x_discrete(labels=c(
    "FF07-OB" = "S-07", "FF07-IB" = "S-07", "FF07-CB" = "S-07",
    "FF04-OB" = "S-04", "FF04-IB" = "S-04", "FF04-CB" = "S-04",
    "FF05-OB" = "S-05", "FF05-IB" = "S-05", "FF05-CB" = "S-05",
    "FF02-OB" = "S-02", "FF02-IB" = "S-02", "FF02-CB" = "S-02",
    "FF08-OB" = "S-08", "FF08-IB" = "S-08", "FF08-CB" = "S-08",
    "FF11-OB" = "S-11", "FF11-IB" = "S-11", "FF11-CB" = "S-11",
    "FF01-OB" = "S-01", "FF01-IB" = "S-01", "FF01-CB" = "S-01",
    "FF03-OB" = "S-03", "FF03-IB" = "S-03", "FF03-CB" = "S-03",
    "FF12-OB" = "S-12", "FF12-IB" = "S-12", "FF12-CB" = "S-12",
    "FF06-OB" = "S-06", "FF06-IB" = "S-06", "FF06-CB" = "S-06",
    "FF09-OB" = "S-09", "FF09-IB" = "S-09", "FF09-CB" = "S-09",
    "FF10-OB" = "S-10", "FF10-IB" = "S-10", "FF10-CB" = "S-10")) 
sites
ggsave(path = output_today, filename = "CommunitySites.tiff", width = 21, height = 7, device='tiff', dpi=300) 
# 2022 = dark
# 2021 = light


## Tally also requested a behavior bar plot

###########################################################
## Unaggregated bat acoustic data
###########################################################

rawbat <- read_csv("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/Inputs/ManualAnalaysis21_22_combined_datetime_PlotType_Guild.csv", 
     col_types = cols(...1 = col_skip()))
# 108989 

rawbat <- rawbat %>% mutate(AUTO.ID = factor(AUTO.ID),
                            manual.id = factor(manual.id),
                            behavior = factor(behavior),
                            guild = factor(guild),
                            year = factor(year),
                            Site = factor(Site), 
                        SitePlot = factor(SitePlot), 
                        PlotType = factor(PlotType)) 

levels(rawbat$manual.id)
table(rawbat$manual.id)
levels(rawbat$AUTO.ID)


rbats.0 <- rbats  %>% filter(manual.id != "Noise") %>% droplevels() %>% 
  mutate(taxa = factor(case_when(
    manual.id == "MYOT" ~ "Myotis", 
    manual.id == "PAUR" ~ "P. auritus", 
    manual.id == "PIPY" ~ "P. pygmaeus", 
    manual.id == "PINA" ~ "P. nathusii", 
    manual.id == "MR1" ~ "Pipistrellus spp.",
    manual.id == "EPNI" ~ "E. nilssonii", 
    manual.id == "LR1" ~ "LR1",
    manual.id == "LR2" ~ "LR2", 
    manual.id == "NYNO" ~ "N. noctula",
    manual.id == "NoID"  ~ "NoID")))


rbats.0 $taxa <- factor(rbats.0 $taxa, levels=c("Myotis", "P. auritus", 
                             "P. pygmaeus", "P. nathusii", "Pipistrellus spp.",
                             "E. nilssonii", "LR1",  "LR2", "N. noctula",
                             "NoID")) 

rbats.0$behavior <- gsub("Both", "Feeding", rbats.0$behavior)
rbats.0$behavior <- factor(rbats.0$behavior)

table(rbats.0$behavior, rbats.0$manual.id)
  #            MYOT  PAUR  PIPY  PINA   MR1  EPNI   LR1   LR2  NYNO  NoID
  # Commuting 61007  1840  4450    22   692 12765   258  1118   231   768
  # Feeding   13775     0   430     0    24  1231     2    11     2    15
  # Social      198   558  6845     0     3   195     3     1     0    81

test <- rbats.0 %>% filter(manual.id == "MYOT") %>% droplevels
table(test$behavior, test$PlotType)
  #           Canopy Interior  Open
  # Commuting  16684    13848 30475
  # Feeding     4135     2526  7114
  # Social        40       32   126

behavplot <- ggplot(data = rbats.0 %>%
                     filter(guild == "SRE") %>% 
                      droplevels()) + 
  aes(x = PlotType, fill = behavior, by = PlotType) +
  geom_bar(position = "fill", stat = "prop") + 
  scale_fill_manual(values = c ("#121722", "#3E4F73", "#C5DCF1")) + 
  theme_classic() + 
  facet_wrap(~taxa) +
  theme(strip.text.x = element_text(
        size = 20, face = "italic")) + 
  theme(legend.title=element_blank(),
        text=element_text(size=25),
        legend.position = "bottom") +
  ylab("") + xlab("")

behavplot
ggsave(path = output_today, filename = "BehaviorFigure.tiff", width = 10, height = 8, device='tiff', dpi=300) 


## Figure 4
cowplot::plot_grid(plotgg2, behavplot, nrow = 1, labels = c("", ""))
# DOesnt really work
# ggsave(path = output_today, filename = "NMDS_BehavFigure.tiff", width = 25, height = 27, device='tiff', dpi=300) 

```


## Run the env.fit analysis 
https://jkzorz.github.io/2020/04/04/NMDS-extras.html

```{r}
bat.env1 <- bat.env %>% remove_rownames %>% column_to_rownames(var="SitePlotYear") %>% as.data.frame()

bat.env2 <- bat.env1 %>% select(-c(Site, year)) 

en1 = envfit(b.mds, bat.env1, permutations = 999, na.rm = TRUE) 
en1

# Goodness of fit:
#              r2 Pr(>r)  
# Site     0.2505  0.043 *
# PlotType 0.0296  0.424  
# year     0.0280  0.151  

en2 = envfit(b.mds, bat.env2, permutations = 999, na.rm = TRUE) 
en2

# ***FACTORS:
# 
# Centroids:
#                    NMDS1   NMDS2
# PlotTypeOpen      0.0516 -0.0254
# PlotTypeInterior -0.0182  0.0537
# PlotTypeCanopy   -0.0334 -0.0283

data.scores = scores(b.mds)
ds <- as.data.frame(data.scores$sites)
ds$SitePlotYear = rownames(ds) 
ds1 <- left_join(ds, bat.env) 

en_coord_cat = as.data.frame(scores(en, "factors")) * ordiArrowMul(en)

plot(b.mds)
plot(en) 
```

