---
title: "MyotisFeeding"
output: html_document
date: "2024-02-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

## Load libraries
library(data.table)
library(tidyverse)
library(beepr)
library(lubridate)
library(purrr)
library(janitor)
library(renv)
library(stringr)
library(beepr)
library(kableExtra)
library(papeR)
library(skimr)
library(vtable)
library(ggdark)
library(RColorBrewer)
library(cowplot)
library(readxl)
library(readr)
library(ggstats)
library(ggpmisc)
library(gginnards)
library(ggplot2)
library(colorBlindness)
library(DHARMa)
library(performance)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(modelsummary)
library(gt)
library(beepr)
library(rgl)
library(vctrs)
library(gamm4)
library(mgcv)
library(itsadug)
library(plot3D)
library(ggeffects)
library(viridis)   #color-blind friendly palette'

mydata <-read_csv("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/ForDryad/5.BatInsectModels/Inputs/BatsInsectsCombined_NightAggregated_Weather_Photoperiod_CanOpen.csv",
                  col_types = cols(...1 = col_skip())) #----LOAD THE DATA

## Setup output directory 
output <- "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/ForDryad/5.BatInsectModels/Outputs"

file.name <- "MyotisFeeding"

todays_date <- Sys.Date()
 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
dir.name
 
output_today <- dir.name
output_today

dir.create(output_today)
output_today
# "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/ForDryad/5.BatInsectModels/Outputs/MyotisFeeding_2024-02-22"

```


## House keeping
```{r}

#---QUICK INITIAL LOOK AT THE 'mydata' DATA OBJECT
str(mydata)
#---fix date format for variable night
mydata$night <- as.Date(mydata$night, "%d.%m.%Y")
#---year as factor
mydata$year <- as.factor(mydata$year)
#---Site as factor
mydata$Site <- as.factor(mydata$Site)
#---SitePlotYear as factor
mydata$SitePlotYear <- as.factor(mydata$SitePlotYear)
#---new insect variable to account for nPhoto
mydata$InsectIndex <- mydata$nInsects / mydata$nPhotos

str(mydata)
head(mydata)
tail(mydata)
dim(mydata)
summary(mydata) 
names(mydata)


#select only manual.id level MYOT and behavior level Feeding
filtered_df <- subset(mydata, manual.id == "MYOT" & behavior == "Feeding")
dim(filtered_df)

summary(filtered_df)

DF <- filtered_df
dim(DF)
#There are no NAs for nInsect or batpass in this subset


#How many observations in 2021 vs 2022
# Create a frequency table for year
frequency_table <- table(DF$year)

# Print the frequency table
print(frequency_table)

#2021 2022 
#293  108 

##############LOOK AT THE INSECT DATA

# Count the number of rows where InsectIndex is 0
num_zeros <- sum(DF$InsectIndex == 0)

# Calculate the total number of rows in the dataframe
total_rows <- nrow(DF)

# Calculate the percentage of rows with value 0 for InsectIndex
percent_zeros <- (num_zeros / total_rows)*100

# Print the result
cat("Percent of rows with value 0 for InsectIndex:", percent_zeros)
#Percent of rows with value 0 for InsectIndex: 16.20948
#That is not so bad
```


## Exploration - transform insect index > 2 = 2 
```{r}
#distribution of values
plot(1:nrow(DF), DF$InsectIndex, 
     pch = 16, col = "blue", 
     main = "Distribution of InsectIndex",
     xlab = "Data Point", ylab = "InsectIndex")

# Add a horizontal line at the mean
abline(h = mean(DF$InsectIndex), col = "red", lty = 2)



range(DF$InsectIndex)
df <- DF

#Replace 4 observations with values greater than 2 in InsectIndexCertain with 2
df$InsectIndex[df$InsectIndex > 2] <- 2 

plot(1:nrow(df), df$InsectIndex, 
     pch = 16, col = "blue", 
     main = "Distribution of InsectIndex",
     xlab = "Data Point", ylab = "InsectIndex")

# Add a horizontal line at the mean
abline(h = mean(df$InsectIndex), col = "red", lty = 2)



##############LOOK AT THE CanOpen variable too

plot(1:nrow(df), df$CanOpen, 
     pch = 16, cex = 0.3, col = "darkgreen", 
     main = "Distribution of CanOpen",
     xlab = "Data Point", ylab = "CanOpen")

# Add a horizontal line at the mean
abline(h = mean(df$CanOpen), col = "red", lty = 2)



##############LOOK AT THE batpass DATA

# Count the number of rows where batpass is 0
num_zeros <- sum(df$batpass == 0)

# Calculate the total number of rows in the dataframe
total_rows <- nrow(df)

# Calculate the percentage of rows with value 0 for batpass
percent_zeros <- (num_zeros / total_rows)*100

# Print the result
cat("Percent of rows with value 0 for batpass:", percent_zeros, "\n")
#Percent of rows with value 0 for batpass: 58.85287 
#That is a lot  - will most likely need a zero-inflated model

# distribution of values

plot(1:nrow(df), df$batpass, 
     pch = 16, col = "blue", 
     main = "Distribution of batpass",
     xlab = "Data Point", ylab = "batpass")

# Add a horizontal line at the mean
abline(h = mean(df$batpass), col = "red", lty = 2)
abline(h = 20, col = "red", lty = 1)
abline(h = 30, col = "green", lty = 1)


#Will have to keep an eye one the outliers, but first check if some SitePlotYear
#have very few observations


#How many observations per SitePlotYear
# Create a frequency table for year
frequency_table <- table(df$SitePlotYear)

# Print the frequency table
print(frequency_table)

```

## Further subsetting
```{r}
# Levels to exclude: < 10 observation nights per SitePlotYear
excluded_levels <- c('FF03-OB-2021', 'FF03-OB-2022', 'FF05-OB-2022', 'FF06-OB-2022', 'FF08-OB-2022', 'FF11-OB-2021')

# Creating a subset excluding specified levels
df_subset <- df[!(df$SitePlotYear %in% excluded_levels), ]

# Dropping excluded levels completely
df_subset$SitePlotYear <- droplevels(df_subset$SitePlotYear, exclude = excluded_levels)

# Create a frequency table for year
frequency_table <- table(df_subset$SitePlotYear)

# Print the frequency table
print(frequency_table)

dim(df) #401 rows
dim(df_subset) #364 rows
```


## Further exploration
```{r}

plot(1:nrow(df_subset), df_subset$batpass, 
     pch = 16, col = "blue", 
     main = "subset SitePlotYear with min 10 observ nights",
     xlab = "Data Point", ylab = "batpass")

# Add a horizontal line at the mean
abline(h = mean(df_subset$batpass), col = "red", lty = 2)
abline(h = 30, col = "red", lty = 1)


#distribution of CanOpen variable for the subsetted data

plot(1:nrow(df_subset), df_subset$CanOpen, 
     pch = 16, cex = 0.3, col = "darkgreen", 
     main = "Distribution of CanOpen",
     xlab = "Data Point", ylab = "CanOpen")

# Add a horizontal line at the mean
abline(h = mean(df_subset$CanOpen), col = "red", lty = 2)



#Not use this - but just for visual exploration
df_subset20 <- df_subset

#Replace x observations with values greater than 20 for batpass with 20
df_subset20$batpass[df_subset20$batpass > 20] <- 20 

#look at subsetted batpass data with max value 20
par(mfrow = c(1, 1))
plot(1:nrow(df_subset20), df_subset20$batpass, 
     pch = 16, col = "blue", 
     main = "subset SitePlotYear with min 10 observ nights, max value 20",
     xlab = "Data Point", ylab = "batpass")

# Add a horizontal line at the mean
abline(h = mean(df_subset20$batpass), col = "red", lty = 2)


#Plot relationship between batpass and insect index to 
#check if consistent pattern between years

ggplot(df_subset, aes(x = InsectIndex, y = batpass)) +
  geom_point() +
  labs(title = "compare years", x = "InsectIndex", y = "batpass") +
  theme_minimal() +
  facet_wrap(~year, scales = "fixed")

ggplot(df_subset20, aes(x = InsectIndex, y = batpass, color=Site)) +
  geom_point() +
  labs(title = "compare years", x = "InsectIndex", y = "batpass") +
  theme_minimal() +
  facet_wrap(~year, scales = "fixed")

#visual exploration of relationship between batpass and CanOpen
ggplot(df, aes(x = CanOpen, y = batpass)) +
  geom_point() +
  labs(title = "", x = "CanOpen", y = "batpass") +
  theme_minimal()  


#################### for interpretation later: check relationship between canopy openness and insect index
#################### important thing is to look for indication of lower insect index at low canopy openness
#################### which could mean that insects are masked by vegetation

#When SitePlotYear < 10 obs nights excluded
ggplot(df_subset, aes(x = CanOpen, y = InsectIndex)) +
  geom_point() +
  labs(title = "no clear relationship between canopy openness and insect index", x = "CanOpen", y = "InsectIndex") +
  theme_minimal() +
  facet_wrap(~year, scales = "fixed", nrow=2)

#All SitePlotYear
ggplot(df, aes(x = CanOpen, y = InsectIndex)) +
  geom_point() +
  labs(title = "no clear relationship between canopy openness and insect index", x = "CanOpen", y = "InsectIndex") +
  theme_minimal() +
  facet_wrap(~year, scales = "fixed", nrow=2)

#When SitePlotYear < 10 obs nights excluded
ggplot(df_subset, aes(x = CanOpen, y = InsectIndex)) +
  geom_point() +
  labs(title = "no clear relationship between canopy openness and insect index", x = "CanOpen", y = "InsectIndex") +
  theme_minimal() 

#All SitePlotYear
ggplot(df, aes(x = CanOpen, y = InsectIndex)) +
  geom_point() +
  labs(title = "no clear relationship between canopy openness and insect index", x = "CanOpen", y = "InsectIndex") +
  theme_minimal()

```



### Fit a GAM
```{r}
df_subset_no_na <- na.omit(df_subset)
dim(df_subset_no_na)

# I will not use the seNorge temperature because T3 is more accurate
# I did not use avg soil moisture per site because of lack of variation (GAMM)
# standardize numerical variables  
# Not sure if standardization is needed for GAMMs, but not wrong either

df_subset_no_na$se.precipStd    <- scale(df_subset_no_na$se.precip)   
df_subset_no_na$T3Std           <- scale(df_subset_no_na$T3)  
df_subset_no_na$SoilMoistureStd <- scale(df_subset_no_na$SoilMoisture)
df_subset_no_na$CanOpenStd      <- scale(df_subset_no_na$CanOpen)
df_subset_no_na$InsectIndexStd  <- scale(df_subset_no_na$InsectIndex)
df_subset_no_na$day_lengthStd   <- scale(df_subset_no_na$day_length)
df_subset_no_na$jnightStd       <- scale(df_subset_no_na$jnight)

summary(df_subset_no_na)

#the bs = "gp" takes care of temporal autocorrelation
m0nb <- gam(batpass ~ 
              s(InsectIndexStd) + 
              s(CanOpenStd)  + 
              s(jnightStd, bs = "gp") + 
              s(day_lengthStd, bs = "gp") +
              s(T3Std) +
              s(SoilMoistureStd) +
              s(se.precipStd) +
              s(InsectIndexStd, CanOpenStd) + 
              s(InsectIndexStd, jnightStd, bs = "gp") + 
              s(InsectIndexStd, day_lengthStd, bs = "gp") +
              s(InsectIndexStd, T3Std) +
              s(InsectIndexStd, SoilMoistureStd) +
              s(InsectIndexStd, se.precipStd) +
              s(year, bs = "re") + s(Site, bs = "re"), method = "ML", family = nb(), data = df_subset_no_na)
summary(m0nb)


m0zip <- gam(batpass ~ 
                     s(InsectIndexStd) + 
                     s(CanOpenStd)  + 
                     s(jnightStd, bs = "gp") + 
                     s(day_lengthStd, bs = "gp") +
                     s(T3Std) +
                     s(SoilMoistureStd) +
                     s(se.precipStd) +
                     s(InsectIndexStd, CanOpenStd) + 
                     s(InsectIndexStd, jnightStd, bs = "gp") + 
                     s(InsectIndexStd, day_lengthStd, bs = "gp") +
                     s(InsectIndexStd, T3Std) +
                     s(InsectIndexStd, SoilMoistureStd) +
                     s(InsectIndexStd, se.precipStd) +
              s(year, bs = "re") + s(Site, bs = "re"), method = "ML", family= "ziP()", data = df_subset_no_na)
summary(m0zip)

#Compare models
AIC(m0nb,m0zip)
#           df      AIC
#m0nb  32.24403 1098.250
#m0zip 83.97260 1126.451


par(mfrow = c(2, 2))
gam.check(m0nb) #looks good
par(mfrow = c(2, 2))
gam.check(m0zip) #looks slightly worse

#######################################################################################
###https://stat.ethz.ch/R-manual/R-devel/library/mgcv/html/gam.selection.html
### perform backwards selection using p-values: 
### that is by sequentially dropping the single term with the highest non-significant 
### p-value from the model and re-fitting, until all terms are significant. 
### Dropped year after all environmental variables dropped

m0nb <- gam(batpass ~ 
              s(InsectIndexStd) + 
              s(CanOpenStd)  + 
              s(day_lengthStd, bs = "gp") +
              s(SoilMoistureStd) +
              s(InsectIndexStd, CanOpenStd) + 
               s(Site, bs = "re"), method = "ML", family = nb(), data = df_subset_no_na)
summary(m0nb)

#Backward elimination
#s(InsectIndexStd,T3Std)           5.210e-05 27.000   0.000  0.9323  
#s(T3Std)                          1.000e+00  1.000   0.017  0.8959 
#s(InsectIndexStd,jnightStd)       1.574e-06 30.000   0.000  0.4444  
#s(jnightStd)                      1.000e+00  1.000   0.002  0.9611  
#s(InsectIndexStd,day_lengthStd)   1.238e-05 30.000   0.000  0.4581
#s(InsectIndexStd,se.precipStd)    1.042e-05 27.000   0.000  0.3644 
#s(InsectIndexStd,SoilMoistureStd) 0.0008203 27.000   0.001  0.3062  
#s(se.precipStd)                   1.0000  1.000   2.876  0.0899 .  
#s(year)                      0.1898  1.000   0.326  0.2075  

#refit with REML
m1nbREML <- gam(batpass ~ 
              s(InsectIndexStd) + 
              s(CanOpenStd)  + 
              s(day_lengthStd, bs = "gp") +
              s(SoilMoistureStd) +
              s(InsectIndexStd, CanOpenStd) + 
              s(Site, bs = "re"), method = "REML", family = nb(), data = df_subset_no_na)
summary(m1nbREML)


par(mfrow = c(2, 2))
gam.check(m1nbREML)  # looks good (an all k-index p-values >>0.05)

#refit with unstandardized variable
M1nbREML <- gam(batpass ~ 
                  s(InsectIndex) + 
                  s(CanOpen)  + 
                  s(day_length, bs = "gp") +
                  s(SoilMoisture) +
                  s(InsectIndex, CanOpen) + 
                  s(Site, bs = "re"), method = "REML", family = nb(), data = df_subset_no_na)
summary(M1nbREML)


par(mfrow = c(2, 2))
gam.check(M1nbREML)

# Avoid "strange numbers": m1nbREML is your model
#summary_output <- summary(m1nbREML)

# Set options to avoid scientific notation and display more digits
#options(scipen = 999, digits = 6)

# Print the modified summary
#print(summary_output)

# Reset options to their default values if needed
#options(scipen = 0, digits = 7)

```

## Plotting predictions
```{r}

#This is my final model
summary(m1nbREML)
#This is my final model unstandardized
summary(M1nbREML)

prediction_data0M <- ggpredict(M1nbREML, c("InsectIndex", "CanOpen"))

fig5a <- plot(prediction_data0M, 
     color = "viridis") + 
  geom_line(linewidth = 1.2) + 
  ggtitle("a.") +
  labs(x = "Insect abundance", 
       y = "Feeding bat passes", 
       color= "Canopy openness") +
  theme(text = element_text(size = 12),    # Adjust the overall text size
        axis.title = element_text(size = 16),  # Adjust the axis title size
        axis.text = element_text(size = 14),   # Adjust the axis text size
        legend.text = element_text(size = 14), # Adjust the legend text size
        legend.title = element_text(size = 16),# Adjust the legend title size
        strip.text.x = element_text(size = 14),
        legend.position = "bottom" # Place the legend at the bottom
  )

fig5a
# ggsave(path = output_today, filename = "Fig5a.tiff", width = 10, height = 8, device='tiff', dpi=300) 



prediction_data1M <- ggpredict(M1nbREML, c("CanOpen", "day_length"))

fig5b <- plot(prediction_data1M, color = "viridis") +
  ggtitle("b.") +
  geom_line(linewidth = 1.2) + 
  labs(x = "Canopy openness", 
       y = "Feeding bat passes", 
       color = "Daylength") +
  theme(text = element_text(size = 12),    # Adjust the overall text size
        axis.title = element_text(size = 16),  # Adjust the axis title size
        axis.text = element_text(size = 14),   # Adjust the axis text size
        legend.text = element_text(size = 14), # Adjust the legend text size
        legend.title = element_text(size = 16),# Adjust the legend title size
        strip.text.x = element_text(size = 14),
        legend.position = "bottom" # Place the legend at the bottom
  )

fig5b

# ggsave(path = output_today, filename = "Fig5b.tiff", width = 10, height = 8, device='tiff', dpi=300) 



prediction_data3 <- ggpredict(M1nbREML, 
  c("InsectIndex", "CanOpen", "SoilMoisture"))

fig5c <- plot(prediction_data3, color = "viridis") +
  geom_line(linewidth = 1.2) + 
  ggtitle("c.") +
  labs(x = "Insect abundance", 
       y = "Feeding bat passes", 
       color= "Canopy openness") +
  theme(text = element_text(size = 12),    # Adjust the overall text size
        axis.title = element_text(size = 16),  # Adjust the axis title size
        axis.text = element_text(size = 14),   # Adjust the axis text size
        legend.text = element_text(size = 14), # Adjust the legend text size
        legend.title = element_text(size = 16),# Adjust the legend title size
        strip.text.x = element_text(size = 14),
        legend.position = "bottom" # Place the legend at the bottom
  )

fig5c
#ggsave(path = output_today, filename = "Fig5c.tiff", width = 10, height = 8, device='tiff', dpi=300) 


### All together now: 

# cowplot::plot_grid(fig5a, fig5b, fig5c, nrow = 3, labels = c("a.", "b.", "c."))
# 
# ggsave(path = output_today, filename = "Fig5.tiff", width = 8, height = 13, device='tiff', dpi=300) 
# ggsave(path = output_today, filename = "Fig5_1.tiff", width = 9, height = 14, device='tiff', dpi=300) 
# ggsave(path = output_today, filename = "Fig5_2.tiff", width = 8, height = 15, device='tiff', dpi=300) 
# ggsave(path = output_today, filename = "Fig5_3.tiff", width = 9, height = 16, device='tiff', dpi=300) 
# ggsave(path = output_today, filename = "Fig5_4.tiff", width = 8, height = 15, device='tiff', dpi=300) 

###########################################################################################
##### Alternative now in the manuscript: 
### Add labels as title 
pt1 <- cowplot::plot_grid(fig5a, fig5b,  ncol = 2)

pt2 <- cowplot::plot_grid(pt1, fig5c, nrow = 2)

pt2

ggsave(path = output_today, filename = "Fig5_alt.tiff", width = 10, height = 13, device='tiff', dpi=300) 
#

### What percent of the feeding bat passes occur when insect abundance is greater than 0.50?

summary(df_subset_no_na)
dim(df_subset_no_na)
# 354  37

test <- df_subset_no_na %>% filter(batpass > 0)
# 145
test1 <- test %>% filter(InsectIndex > 0.50)
#22
# 22/145
# = 15%

test2 <- test %>% filter(InsectIndex > 0.30)
#32
# 32/145
# = 22%

test3 <- test %>% filter(InsectIndex > 0.20)
# 53
# 53/145
# = 37%

testx <- df_subset_no_na %>% filter(batpass > 5)
test4 <- testx %>% filter(InsectIndex > 0.50)
# 6/33
# = 0.1818182
```



## Supplementary materials
```{r}
#Some interpretation of influence of explanatory variables
#---------Temperature
#T3
m.T3  <- gam(InsectIndex ~ s(T3 ) +  s(Site, bs = "re"), metod="REML", data = df_subset_no_na)
summary(m.T3) #significant inluence but edf = 1.267 is nearly 1, so can also use linear model

# Generate predicted values
predictionsT3  <- ggpredict(m.T3, terms = c("T3"))
# Create prediction plot
plotpredictionsT3 <- plot(predictionsT3)
# Display the plot
print(plotpredictionsT3)


# Customize prediction plot
figs3a <- plot(predictionsT3) +
  labs(x = "Temperature", y = "Insect abundance") +
  theme(text = element_text(size = 10),    # Adjust the overall text size
        axis.title = element_text(size = 12),  # Adjust the axis title size
        axis.text = element_text(size = 12),   # Adjust the axis text size
        legend.text = element_text(size = 12) # Adjust the legend text size
        # Adjust the legend title size
  )

figs3a

#-------jnight

#jnight / FOUND non-linear decline with season /
m.jnight <- gam(InsectIndex ~ s(jnight ) +  s(Site, bs = "re"), metod="REML", data = df)
summary(m.jnight) #

  

# Generate predicted values
predictionsm.jnight <- ggpredict(m.jnight, terms = c("jnight"))
# Create prediction plot
plotpredictionsm.jnight <- plot(predictionsm.jnight)
# Display the plot
print(plotpredictionsm.jnight)



# Customize prediction plot
figs3b <- plot(predictionsm.jnight) +
  labs(x = "Julian night", y = "Insect abundance") +
  theme(text = element_text(size = 10),    # Adjust the overall text size
        axis.title = element_text(size = 12),  # Adjust the axis title size
        axis.text = element_text(size = 12),   # Adjust the axis text size
        legend.text = element_text(size = 12) # Adjust the legend text size
        # Adjust the legend title size
  )

# Arrange the plots side by side
cowplot::plot_grid(figs3a, figs3b, ncol = 2, 
                   labels = c("a.", "b.")) 

ggsave(path = output_today, filename = "FigS3.tiff", width = 8, height = 5, device='tiff', dpi=300)

cowplot::plot_grid(figs3a, figs3b, nrow = 2, 
                   labels = c("a.", "b.")) 
ggsave(path = output_today, filename = "FigS3_1.tiff", width = 8, height = 9, device='tiff', dpi=300)






#SoilMoistureStd ~ as.numeric(se.precipStd)
# Your linear model
mmoist <- lm(SoilMoistureStd ~ as.numeric(se.precipStd), data = df_subset_no_na)
summary(mmoist)
cor.test(df_subset_no_na$SoilMoistureStd, df_subset_no_na$se.precipStd)
# Create a scatter plot with regression line
ggplot(df_subset_no_na, aes(x = se.precipStd, y = SoilMoistureStd)) +
  geom_point(size = 2, shape = 21, fill = "blue") +  # Scatter plot
  geom_smooth(method = "lm", se = FALSE, color = "red") +  # Regression line
  ggtitle("Linear Regression Model Visualization") +
  labs(x = "Standardized Precipitation", y = "Standardized Soil Moisture") +
  theme_minimal()
 


###########################################################################################
#

### FIGURE S2 
#Some more interpretation of influence of explanatory variables

#------------batpass versus insects

mInsect <- gam(batpass ~ s(InsectIndex) +  s(Site, bs = "re"), metod="REML", data = df_subset)
summary(mInsect) #

#Estimate Std. Error t value Pr(>|t|)  
#(Intercept)    3.293      1.574   2.092   0.0371 *
#
#
#Approximate significance of smooth terms:
#  edf Ref.df      F p-value    
#s(InsectIndex) 6.109  7.247  1.931  0.0655 .  
#s(Site)        9.244 10.000 15.615  <2e-16 ***

#R-sq.(adj) =  0.322   Deviance explained = 35.1%

#Model validation
par(mfrow = c(2, 2))
gam.check(mInsect)

#Basis dimension (k) checking results. Low p-value (k-index<1) may
#indicate that k is too low, especially if edf is close to k'.
#
#                  k'   edf k-index p-value
#s(InsectIndex)  9.00  6.11    1.07    0.92
#s(Site)        11.00  9.24      NA      NA

# Generate predicted values
predictionsmInsect <- ggpredict(mInsect, terms = c("InsectIndex"))
# Create prediction plot
plotpredictionsmInsect <- plot(predictionsmInsect)
# Display the plot
print(plotpredictionsmInsect)



# Customize prediction plot
plotpredictionsmInsect <- plot(plotpredictionsmInsect) +
  labs(x = "Insect abundance", y = "Feeding bat passes") +
  ggtitle("") + 
  theme(text = element_text(size = 16),    # Adjust the overall text size
        axis.title = element_text(size = 18),  # Adjust the axis title size
        axis.text = element_text(size = 18),   # Adjust the axis text size
        legend.text = element_text(size = 18) # Adjust the legend text size
        # Adjust the legend title size
  ) +
  
  geom_point(data = df, 
             aes(x = InsectIndex, y = batpass), 
             size = 2, alpha = 0.3,  
             color = "#f57969")  

print(plotpredictionsmInsect)
figs2a <- plotpredictionsmInsect

#------------CanOpen versus insects

mCanOpen <- gam(InsectIndex ~ s(CanOpen, k=4) +  s(Site, bs = "re"), metod="REML", data = df_subset)
summary(mCanOpen) #

#Model validation
par(mfrow = c(2, 2))
gam.check(mCanOpen)

# Generate predicted values
predictionsmCanOpen <- ggpredict(mCanOpen, terms = c("CanOpen"))
# Create prediction plot
plotpredictionsmCanOpen <- plot(predictionsmCanOpen)
# Display the plot
print(plotpredictionsmCanOpen)

# Customize prediction plot
plotpredictionsmCanOpen2 <- plot(predictionsmCanOpen) +
  labs(x = "Canopy openness", y = "Insect abundance") +
  theme(text = element_text(size = 16),    # Adjust the overall text size
        axis.title = element_text(size = 18),  # Adjust the axis title size
        axis.text = element_text(size = 18),   # Adjust the axis text size
        legend.text = element_text(size = 18) # Adjust the legend text size
        # Adjust the legend title size
  ) + ggtitle("") +
  
  geom_point(data = df, aes(x = CanOpen, y = InsectIndex), 
             size = 2, alpha = 0.3,  # Adjust transparency (0: completely transparent, 1: fully opaque)
             color = "#62302a") + 
  xlim(c(0.16, 0.55)) 
print(plotpredictionsmCanOpen2)
figs2b <- plotpredictionsmCanOpen2


# Arrange the plots side by side
cowplot::plot_grid(figs2a, figs2b, nrow = 2, labels = c("a.", "b."))

ggsave(path = output_today, filename = "FigS2.tiff", width = 8, height = 7, device='tiff', dpi=300)

ggsave(path = output_today, filename = "FigS2_1.tiff", width = 8, height = 10, device='tiff', dpi=300)

ggsave(path = output_today, filename = "FigS2_2.tiff", width = 8, height = 12, device='tiff', dpi=300)

cowplot::plot_grid(figs2a, figs2b, ncol = 2, labels = c("a.", "b."))
ggsave(path = output_today, filename = "FigS2_3.tiff", width = 8, height = 5, device='tiff', dpi=300)

# Customize prediction plot - different axis extents
plotpredictionsmInsect <- plot(plotpredictionsmInsect) +
  labs(x = "Insect abundance", y = "Feeding bat passes") +
  ggtitle("") + 
  theme(text = element_text(size = 16),    # Adjust the overall text size
        axis.title = element_text(size = 18),  # Adjust the axis title size
        axis.text = element_text(size = 18),   # Adjust the axis text size
        legend.text = element_text(size = 18) # Adjust the legend text size
        # Adjust the legend title size
  ) +
  
  geom_point(data = df, 
             aes(x = InsectIndex, y = batpass), 
             size = 2, alpha = 0.3,  
             color = "#f57969")  

print(plotpredictionsmInsect)
figs2a <- plotpredictionsmInsect

#------------CanOpen versus insects

mCanOpen <- gam(InsectIndex ~ s(CanOpen, k=4) +  s(Site, bs = "re"), metod="REML", data = df_subset)
summary(mCanOpen) #

#Model validation
par(mfrow = c(2, 2))
gam.check(mCanOpen)

# Generate predicted values
predictionsmCanOpen <- ggpredict(mCanOpen, terms = c("CanOpen"))
# Create prediction plot
plotpredictionsmCanOpen <- plot(predictionsmCanOpen)
# Display the plot
print(plotpredictionsmCanOpen)

# Customize prediction plot
plotpredictionsmCanOpen2 <- plot(predictionsmCanOpen) +
  labs(x = "Canopy openness", y = "Insect abundance") +
  theme(text = element_text(size = 16),    # Adjust the overall text size
        axis.title = element_text(size = 18),  # Adjust the axis title size
        axis.text = element_text(size = 18),   # Adjust the axis text size
        legend.text = element_text(size = 18) # Adjust the legend text size
        # Adjust the legend title size
  ) + ggtitle("") + 
  
  geom_point(data = df, aes(x = CanOpen, y = InsectIndex), 
             size = 2, alpha = 0.3,  # Adjust transparency (0: completely transparent, 1: fully opaque)
             color = "#62302a") 
print(plotpredictionsmCanOpen2)
figs2b <- plotpredictionsmCanOpen2

cowplot::plot_grid(figs2a, figs2b, ncol = 2, labels = c("a.", "b."))

ggsave(path = output_today, filename = "FigS2_4.tiff", width = 8, height = 5, device='tiff', dpi=300)

#######################################################################################
######### 3D plot for the paper #################################################
#######################################################################################

df_subset_no_na <- na.omit(df_subset)
dim(df_subset_no_na)
df_subset
dim(df_subset)

# Create a frequency table for year
frequency_table_no_na <- table(df_subset_no_na$SitePlotYear)

# Print the frequency table
print(frequency_table_no_na) #still minimum 10 obs per SiteYear

s(InsectIndex) + 
  s(CanOpen)  + 
  s(day_length, bs = "gp") +
  s(SoilMoisture) +
  s(InsectIndex, CanOpen) + 
  s(Site, bs = "re")

new_data <- expand.grid(
  InsectIndex = seq(min(df_subset_no_na$InsectIndex), max(df_subset_no_na$InsectIndex), length.out = 50),
  CanOpen = unique(df_subset_no_na$CanOpen),
  day_length = mean(df_subset_no_na$day_length),
  SoilMoisture = 1600,
  Site = unique(df_subset_no_na$Site))

head(new_data)
# Make predictions
predictions <- predict(M1nbREML, new_data, type = "response", se.fit = TRUE)


# Extract predicted values and standard errors
pred_values <- predictions$fit
se <- predictions$se.fit

# Combine predictions with grid data
prediction_data <- cbind(new_data, pred_values, se)

head(prediction_data)
tail(prediction_data)
# Create a 3D surface plot with rgl
with(prediction_data, {
  plot3d( CanOpen, InsectIndex, matrix(pred_values, ncol = length(unique(prediction_data$InsectIndex))),
         col = terrain.colors(100), type = "h", size = 1, 
         xlab = "", ylab = "", zlab = "",
         main = "")
  rgl.postscript("3d_plot FINAL.eps", fmt = "eps")
})

```

