---
title: "Myotis_Feeding_GAM"
output: html_document
date: "2024-02-13"
---


```{r}
library(rgl)
library(vctrs)
library(plotly)
library(ggplot2)
library(dplyr)
library(gamm4)
library(mgcv)
library(itsadug)
library(plot3D)
library(readr)
library(stringr)
library(beepr)
library(kableExtra)
library(papeR)
library(skimr)
library(vtable)
library(ggdark)
library(RColorBrewer)
library(cowplot)
library(readxl)
library(readr)
library(ggstats)
library(ggpmisc)
library(gginnards)
library(colorBlindness)
library(vegan) 
library(TMB)
library(glmmTMB)
library(DHARMa)

## Setup output directory 
output <- "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/ForDryad/5.BatInsectModels/Outputs"

file.name <- "M.Commut_GAM"

todays_date <- Sys.Date()
 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
dir.name
 
output_today <- dir.name
output_today

dir.create(output_today)
output_today
# "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/ForDryad/5.BatInsectModels/Outputs/M.Commut_GAM_2024-02-13"


```

## Import the data 
```{r}
mydata <-read_csv("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/3. Follo Forest 2021-2023/Manuscripts/Analyses/ForDryad/2.AggregationCombineCovariates/NightAgg_BatsInsects_SRE_Open/Outputs/NightAggBatsInsects_2024-02-01/SREbatsInsects_se.Weatherphoto.csv",
                  col_types = cols(...1 = col_skip()))#----LOAD THE DATA
# 2441 obs 26 vars 

#---QUICK INITIAL LOOK AT THE 'mydata' DATA OBJECT
str(mydata)
#---fix date format for variable night
mydata$night <- as.Date(mydata$night, "%d.%m.%Y")
#---year as factor
mydata$year <- as.factor(mydata$year)
#---Site as factor
mydata$Site <- as.factor(mydata$Site)
#---SitePlotYear as factor
mydata$SitePlotYear <- as.factor(mydata$SitePlotYear)
#---new insect variable to account for nPhoto
mydata$InsectIndex <- mydata$nInsects / mydata$nPhotos

str(mydata)
head(mydata)
tail(mydata)
dim(mydata)
summary(mydata) 
names(mydata)
```


## Data exploration 

```{r}


#select only manual.id level MYOT and behavior level Feeding
filtered_df <- subset(mydata, manual.id == "MYOT" & behavior == "Feeding")
dim(filtered_df)

summary(filtered_df)

DF <- filtered_df
dim(DF)
# 401  27
summary(DF)
#There are no NAs for nInsect or batpass in this subset


#How many observations in 2021 vs 2022
# Create a frequency table for year
frequency_table <- table(DF$year)

# Print the frequency table
print(frequency_table)
#2021 2022 
#293  108 

##############LOOK AT THE INSECT DATA

# Count the number of rows where InsectIndex is 0
num_zeros <- sum(DF$InsectIndex == 0)

# Calculate the total number of rows in the dataframe
total_rows <- nrow(DF)

# Calculate the percentage of rows with value 0 for InsectIndex
percent_zeros <- (num_zeros / total_rows)*100
# Print the result
cat("Percent of rows with value 0 for InsectIndex:", percent_zeros, "/n")
#Percent of rows with value 0 for InsectIndex: 16.20948
#That is not so bad

#distribution of values
plot(1:nrow(DF), DF$InsectIndex, 
     pch = 16, col = "blue", 
     main = "Distribution of InsectIndex",
     xlab = "Data Point", ylab = "InsectIndex")

# Add a horizontal line at the mean
abline(h = mean(DF$InsectIndex), col = "red", lty = 2)

range(DF$InsectIndex)
df <- DF

#Replace 4 observations with values greater than 2 in InsectIndexCertain with 2
df$InsectIndex[df$InsectIndex > 2] <- 2 

plot(1:nrow(df), df$InsectIndex, 
     pch = 16, col = "blue", 
     main = "Distribution of InsectIndex",
     xlab = "Data Point", ylab = "InsectIndex")

# Add a horizontal line at the mean
abline(h = mean(df$InsectIndex), col = "red", lty = 2)


##############LOOK AT THE CanOpen variable too
plot(1:nrow(df), df$CanOpen, 
     pch = 16, cex = 0.3, col = "darkgreen", 
     main = "Distribution of CanOpen",
     xlab = "Data Point", ylab = "CanOpen")

# Add a horizontal line at the mean
abline(h = mean(df$CanOpen), col = "red", lty = 2)


##############LOOK AT THE batpass DATA
# Count the number of rows where batpass is 0
num_zeros <- sum(df$batpass == 0)

# Calculate the total number of rows in the dataframe
total_rows <- nrow(df)

# Calculate the percentage of rows with value 0 for batpass
percent_zeros <- (num_zeros / total_rows)*100

# Print the result
cat("Percent of rows with value 0 for batpass:", percent_zeros, "/n")
#Percent of rows with value 0 for batpass: 58.85287 
#That is a lot  - will most likely need a zero-inflated model

# distribution of values
plot(1:nrow(df), df$batpass, 
     pch = 16, col = "blue", 
     main = "Distribution of batpass",
     xlab = "Data Point", ylab = "batpass")

# Add a horizontal line at the mean
abline(h = mean(df$batpass), col = "red", lty = 2)
abline(h = 20, col = "red", lty = 1)
abline(h = 30, col = "green", lty = 1)


#Will have to keep an eye one the outliers, but first check if some SitePlotYear
#have very few observations


#How many observations per SitePlotYear
# Create a frequency table for year
frequency_table <- table(df$SitePlotYear)

# Print the frequency table
print(frequency_table)

# Levels to exclude: < 10 observation nights per SitePlotYear
excluded_levels <- c('FF03-OB-2021', 'FF03-OB-2022', 'FF05-OB-2022', 'FF06-OB-2022', 'FF08-OB-2022', 'FF11-OB-2021')

# Creating a subset excluding specified levels
df_subset <- df[!(df$SitePlotYear %in% excluded_levels), ]

# Dropping excluded levels completely
df_subset$SitePlotYear <- droplevels(df_subset$SitePlotYear, exclude = excluded_levels)

# Create a frequency table for year
frequency_table <- table(df_subset$SitePlotYear)

# Print the frequency table
print(frequency_table)

dim(df) #401 rows
dim(df_subset) #364 rows

plot(1:nrow(df_subset), df_subset$batpass, 
     pch = 16, col = "blue", 
     main = "subset SitePlotYear with min 10 observ nights",
     xlab = "Data Point", ylab = "batpass")

# Add a horizontal line at the mean
abline(h = mean(df_subset$batpass), col = "red", lty = 2)
abline(h = 30, col = "red", lty = 1)


#distribution of CanOpen variable for the subsetted data

plot(1:nrow(df_subset), df_subset$CanOpen, 
     pch = 16, cex = 0.3, col = "darkgreen", 
     main = "Distribution of CanOpen",
     xlab = "Data Point", ylab = "CanOpen")

# Add a horizontal line at the mean
abline(h = mean(df_subset$CanOpen), col = "red", lty = 2)



#Not use this - but just for visual exploration
df_subset20 <- df_subset

#Replace x observations with values greater than 20 for batpass with 20
df_subset20$batpass[df_subset20$batpass > 20] <- 20 

#look at subsetted batpass data with max value 20
par(mfrow = c(1, 1))
plot(1:nrow(df_subset20), df_subset20$batpass, 
     pch = 16, col = "blue", 
     main = "subset SitePlotYear with min 10 observ nights, max value 20",
     xlab = "Data Point", ylab = "batpass")

# Add a horizontal line at the mean
abline(h = mean(df_subset20$batpass), col = "red", lty = 2)
```

